services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r Final\ Portfolio/backend/requirements.txt
    startCommand: gunicorn 'Final Portfolio.backend.main:main'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
  - type: web
    name: react-frontend
    env: static
    buildCommand: cd Final\ Portfolio/frontend && npm install && npm run build
    staticPublishPath: Final\ Portfolio/frontend/build